# Lint: interrogate configuration parameters
[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 88
exclude = ["setup.py", "docs", "build"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 0
quiet = false
whitelist-regex = []
color = true
generate-badge = "."
badge-format = "svg"

# Lint: black configuration parameters
[tool.black]
line-length = 100
include = '\.pyi?$'
extend-exclude = '''venv'''

# Lint: isort configuration parameters
[tool.isort]
profile = "black"

# Lint: flake8 configuration parameters
[tool.flake8]
exclude = [".git", "__pycache__", "docs", "build", "dist", "venv", "conda-env"]
max-line-length = 100
ignore = ["E203", "E501", "W503"]
max-complexity = 18

# Lint: mypy configuration parameters
[tool.mypy]
# Disallow dynamic typing
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_generics = false
disallow_any_explicit = false
disallow_subclassing_any = false

# Disallow untyped definitions and calls
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false

# None and optional handling
no_implicit_optional = false

# Configuring warnings
warn_unused_ignores = false
warn_no_return = true
warn_return_any = false
warn_redundant_casts = false

# Misc things
strict_equality = false

# Config file
warn_unused_configs = false
exclude = ["venv", "conda-env/"]

# missing imports
ignore_missing_imports = true

no_warn_no_return = true

# Lint: docformatter configuration parameters
[tool.docformatter]
recursive = true
wrap-summaries = 80
wrap-descriptions = 80
blank = true

# Lint: pylint configuration parameters
[tool.pylint]
enable = "W"
ignore-paths = [
    "^src/services/venv/.*$",
    "^src/services/tests/.*$",
    "^src/api/backend/tests/.*$",
]
fail-on = "E,F,W,C,R"
fail-under = 8.2
recursive = "n"
max-line-length = 100
disable = "E0401,W0221,R0903"

# pytest configuration parameters
[tool.pytest.ini_options]
pythonpath = ["src/module/src"]
