name: Update Badge

on:
  # push:
  pull_request:

jobs:
  create_badge:
    name: Create badge
    runs-on: ubuntu-22.04
    steps:
      # clones current repository
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: df35ac7e1890b43486f992f825c6fbcc
          filename: test.json
          label: Hello
          message: World
          color: orange

      # - uses: NejcZdovc/comment-pr@v2
      #   with:
      #     file: "results.html"
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: comment PR
      #   uses: machine-learning-apps/pr-comment@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     path: "results.html"

      # install python
      - name: Setup Python
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: "3.9"

      # install project depedencies
      - name: Install dependencies
        run: |
          pip install pytest==7.2.0 pytest-cov==4.0.0 pytest-md pytest-emoji pytest-html
          pytest --html "results.html"

      # - name: Run pytest
      #   uses: pavelzw/pytest-action@v2
      #   with:
      #     verbose: true
      #     emoji: true
      #     job-summary: true
      #     click-to-expand: true
      #     report-title: 'Test Report'

      

      - name: Convert HTML to Markdown
        id: html2markdown
        if: always()
        uses: rknj/html2markdown@v1.1.0
        with:
          html-file: "results.html"

      - name: comment PR
        run: ls

      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ${{ steps.html2markdown.outputs.markdown-file }}
