name: Update Badge

on:
  push:
  pull_request:

jobs:
  create_badge:
    name: Create badge
    runs-on: ubuntu-22.04
    steps:
      # clones current repository
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: df35ac7e1890b43486f992f825c6fbcc
          filename: test.json
          label: Hello
          message: World
          color: orange

      - uses: NejcZdovc/comment-pr@v2
        with:
          file: "results.html"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
