# BACKEND module deployment workflow
name: "CD Pipeline BACK"

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Image Name"
        required: false
        default: lh-maz-pop-back
        type: string
      tag_name:
        description: "Tag Name"
        required: false
        default: pop-back
        type: string

jobs:
  # call semantic version reusable workflow
  versioning:
    name: CD
    uses: ./.github/workflows/reusable_semversion.yml
    with:
      tag_prefix: ${{ inputs.tag_name }}/v
      tag_release: true
      module_path: ./src/mymodule
    secrets:
      GIT_TOKEN: ${{ secrets.TOKEN_PROTECTED_TAG }}

  build_and_push:
    name: CD / Publish Docker Image
    runs-on: ubuntu-22.04
    needs: versioning
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Extract Docker Image Name
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
          tags: |
            type=match,pattern=${{ inputs.tag_name }}/v(\d.\d.\d),group=1
            type=sha
            type=raw, value=${{ needs.versioning.outputs.sem_version }}

  changelog_generator:
    name: CD
    needs: [build_and_push, versioning]
    uses: ./.github/workflows/reusable_changelog.yml
    with:
      module: mypkg
      module_dir: src/mymodule
      version: ${{ needs.versioning.outputs.sem_version }}
      fromTag: mypkg/v${{ needs.versioning.outputs.prev_version }}
      toTag: ${{ needs.versioning.outputs.version }}
      release_title: ${{ needs.versioning.outputs.version }}
    secrets:
      GIT_TOKEN: ${{ secrets.TOKEN_PROTECTED_TAG }}
