name: CI Pipeline BACK

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths:
      - src/api/backend/**
  workflow_dispatch:

jobs:
  # call ci reusable workflow
  lint_and_test:
    name: CI
    uses: ./.github/workflows/reusable_ci.yml
    with:
      sonar_project_dir: ./src/mymodule

    secrets:
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
