name: CI Pipeline MAIN

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "src/**"
      - ".github/workflows/ci**"
      - "!.github/workflows/ci_main.yaml"

jobs:
  lint_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo CI job
        run: |
          echo "running CI Pipeline"
