name: "Commit Message Check"
on:
  # push:
  #   branches:
  #     - feat/commit-checker
  pull_request:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      # clones current repository
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Commit Message Type
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^AB#[0-9]+ (feat|fix|test|docs|chore|style|refactor|ci|cd).*"
          error: 'You need to follow conventional commit type "feat|fix|test|docs|chore|style|refactor|ci|cd" in the title line. Please see https://github.com/angular/angular/blob/68a6a07/CONTRIBUTING.md#-commit-message-format for examples'
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Subject Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: "^.{0,51}(\n.*)*$"
          error: "The maximum line length of 50 characters is exceeded."
          excludeDescription: "true" # optional: this excludes the description body of a pull request
          excludeTitle: "true" # optional: this excludes the title of a pull request
          checkAllCommitMessages: "true" # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true

      - name: Check Subject No Capitalize
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^AB#[0-9]+ (feat|fix|test|docs|chore|style|refactor|ci|cd): [a-z].*"
          error: "Don't capitalize the first letter in the commit subject"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Subject No Dot
        if: ${{ success() || failure() }}
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "[^\\.]$"
          error: "Don't use dot (.) at the end of the commit subject"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}
