# Reusable workflow to release a tag
name: "Reusable Tag Release"

on:
  # trigger event to be called from a caller workflow
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: "v"
        description: "version tag"
      tag_message:
        required: false
        type: string
        default: "Releasing version v0.0.1"
        description: "Message for the tag release"

    secrets:
      GIT_TOKEN:
        required: false

jobs:
  # tag release generator
  create_tag:
    runs-on: ubuntu-22.04
    name: Tag Release

    steps:
      # clones current repository
      - name: Checkout current repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0 # fetch the whole repo history

      # release tag version on repository
      - name: Tag Release
        uses: rickstaa/action-create-tag@v1.5.4
        with:
          tag: ${{ inputs.tag }}
          message: ${{ inputs.tag_message }}
          github_token: ${{ secrets.GIT_TOKEN }}
