# Semantic Versioning workflow
# SemVersion number is based in the conventional commit types
# bug,fix,style,docs,etc ------------> increase patch number
# feat ----------------------------->  increase minor number
# feat! -----------------------------> increase major number
# version = major.minor.patch
# e.g.
# version = 0.1.0      --------> major=0 minor=1 patch=0
# there is an option to enable BREAKING CHANGE in the commit footer as well
# more info about this action can be found on https://github.com/PaulHatch/semantic-version
name: "Semantic Versioning Reusable"

on:
  workflow_call:
    inputs:
      tag_prefix:
        required: false
        type: string
        default: "v"
        description: "tag name for the application or module"
      module_path:
        required: false
        type: string
        default: "."
        description: "path to the application or module directory"
      tag_release:
        required: false
        type: boolean
        default: false
        description: "release a tag (default: false)"

    # output version to be used in the caller workflow
    outputs:
      version:
        description: "tag version generated"
        value: ${{ jobs.versioning_generator.outputs.version }}
      prev_version:
        description: "previous tag version"
        value: ${{ jobs.versioning_generator.outputs.prev_version }}

    secrets:
      GIT_TOKEN:
        required: true

jobs:
  # versioning system generator
  versioning_generator:
    runs-on: ubuntu-22.04
    name: Sem Version Generator

    outputs:
      version: ${{ steps.print_version.outputs.semver }}
      prev_version: ${{ steps.print_version.outputs.prevsemver }}

    steps:
      # clones current repository
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch the whole repo history

      # calculate version tag based on codebase commit types
      - uses: paulhatch/semantic-version@v5.0.0-beta2
        id: generated_version
        with:
          # The prefix to use to identify tags
          tag_prefix: "${{ inputs.tag_prefix }}"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "/^AB#[0-9]+ feat!:.*$/"
          # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
          major_regexp_flags: "g"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "/^AB#[0-9]+ feat:.*$/"
          # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
          minor_regexp_flags: "g"
          # A string to determine the format of the version output
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: ${{ inputs.module_path }}
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: true
          # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
          search_commit_body: false

      # print new tag version
      - name: Echo tag version
        id: print_version
        run: |
          echo "Tag: ${{ steps.generated_version.outputs.version_tag }}"
          echo "Semver: ${{ steps.generated_version.outputs.version }}"
          echo "Prev tag: ${{ steps.generated_version.outputs.previous_version }}"
          echo "Prev commit: ${{ steps.generated_version.outputs.previous_commit }}"
          echo "semver=${{ steps.generated_version.outputs.version_tag }}" >> $GITHUB_OUTPUT
          echo "prevsemver=${{ steps.generated_version.outputs.previous_version }}" >> $GITHUB_OUTPUT

      # release tag version on repository
      - name: Tag Release
        if:  ${{ inputs.tag_release}}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.generated_version.outputs.version_tag }}
          message: "Releasing version ${{ steps.generated_version.outputs.version_tag }}"
          github_token: ${{ secrets.GIT_TOKEN }}
