name: Preflight

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - PROD
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  
jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  # release generator job
  release:
    runs-on: ubuntu-22.04
    name: Create Release
    
    steps:
      # clones current repository
      - name: Clone Repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0 # fetch the whole repo history         

      # Set release date as year-month-day: YYYY-MM-DD.
      - name: Set Release Date
        run: |
          echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "Hola: $NOW"
      # Set release date as year-month-day: YYYY-MM-DD.
      - name: Set Release Date
        run: |
          echo "Hola: $NOW"
      # Set release date as year-month-day: YYYY-MM-DD.
      - name: Set Release Date
        run: |
          echo ${{ github.event.repository.updated_at}} | sed 's|T.*||g'
          
          
