name: Preflight

on:
  - pull_request
  - push

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  # release generator job
  release:
    runs-on: ubuntu-22.04
    name: Create Release
    
    steps:
      # clones current repository
      - name: Clone Repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0 # fetch the whole repo history         

      # Set release date as year-month-day: YYYY-MM-DD.
      - name: Set Release Date
        run: |
          echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "Hola: $NOW"
      # Set release date as year-month-day: YYYY-MM-DD.
      - name: Set Release Date
        run: |
          echo "Hola: $NOW"
      # Set release date as year-month-day: YYYY-MM-DD.
      - name: Set Release Date
        run: |
          echo ${{ github.event.repository.updated_at}} | sed 's/:/./g'
          
          
